apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hejle/immich-argocd.git
    targetRevision: master
    path: argocd # this file isn't rendered; we just need something valid #TODO
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# 0) CloudNativePG operator (Helm)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: cloudnative-pg
    repoURL: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
    targetRevision: 0.26.0
    helm:
      skipCrds: false
      values: |
        createCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
---
# 1) CNPG Cluster (Kustomize -> CRDs apply after operator is up)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Hejle/immich-argocd.git #TODO
    targetRevision: master
    path: infra/cnpg-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
---
# 2) Immich (Helm, Redis enabled, uses existingClaim for the library PVC)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # (1) Helm (OCI)
    - repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      chart: immich
      targetRevision: 0.10.0
      helm:
        values: |
          image:
            tag: v2.1.0

          valkey:
            enabled: true

          immich:
            persistence:
              library:
                enabled: true
                existingClaim: immich-library

            env:
              DB_HOSTNAME: immich-db-rw
              DB_PORT: "5432"
              DB_DATABASE_NAME: immich
              REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'

            envFrom:
              - secretRef:
                  name: immich-db-app-env

          ingress:
            main:
              enabled: true
              className: traefik
              hosts:
                - host: immich.hejlepi.local
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - immich.hejlepi.local
                  secretName: hejlepi-local-tls

          controllers:
            main:
              containers:
                main:
                  image:
                    tag: v2.1.0

    # (2) Your Kustomize bits (PVC, redirects, etc.)
    - repoURL: https://github.com/Hejle/immich-argocd.git
      targetRevision: master
      path: immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
